services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

  mysql:
    image: mysql:8.0.41
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: defaultDB
      MYSQL_USER: default
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ../exchange_data/mysql_data:/var/lib/mysql

  eureka: 
    build: ../../exchange/eureka/
    container_name: eureka
    restart: unless-stopped
    ports:
      - "19090:19090"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
    networks:
      - default
      - outside

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=default
      - GF_SECURITY_ADMIN_PASSWORD=1234
    ports:
      - "3000:3000"
    volumes:
      - ../exchange_data/grafana-data:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    command: >
      postgres
      -c shared_preload_libraries=timescaledb,pg_stat_statements
      
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=timescaledb
    volumes:
      - ../exchange_data/timescaledb_data:/var/lib/postgresql/data

networks:
  outside:
    external: true
