KafkaServer {
	org.apache.kafka.common.security.plain.PlainLoginModule required
	username="admin"
	password="1234"
	user_default="1234";
};
Client {
	org.apache.kafka.common.security.plain.PlainLoginModule required
	username="default"
	password="1234";
};
