# Cassandra ?? ??
connector.name=cassandra-connector
cassandra.host=localhost
cassandra.port=9042
cassandra.username=default
cassandra.password=1234
cassandra.config=/home/jun/cassandra-connector/cassandra.yaml

# Kafka ?? ??
kafka.producer.bootstrap.servers=localhost:9092
kafka.producer.security.protocol=SASL_PLAINTEXT
kafka.producer.sasl.mechanism=PLAIN
kafka.producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="default" password="1234";

# ?? ??
topic.prefix=cassandra

# Cassandra CDC ??
snapshot.mode=NEVER
cassandra.keyspace.include=exchange
cassandra.table.include.list=exchange.matched_order
commit.log.relocation.dir=/home/jun/docker/exchange_data/cassandra_data_dc1_node1/cdc_raw
cassandra.cdc.directory=/home/jun/docker/exchange_data/cassandra_data_dc1_node1/cdc_raw
offset.backing.store.dir=/home/jun/cassandra-connector
commit.log.real.time.processing.enabled=true
commit.log.marked.complete.poll.interval.ms=100
poll.interval.ms=100

# ?? ??
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

# ?? ??
transforms=unwrap
transforms.unwrap.type=org.apache.kafka.connect.transforms.ExtractField$Value
transforms.unwrap.field=after
