server:
  port: 8081

spring:
  profiles:
    active: dev

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  master:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:${SHARD_MASTER_PORT}/Exchange
        username: root
        password: 1234
  slave:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:${SHARD_SLAVE_PORT}/Exchange
        username: root
        password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379